Repository Arquisoft/lomap_en1a, pull requests merged in 2023-04, with the labels that each got.

#116 Deployment modifications
  .github/workflows/lomap_en1a.yml
  restapi/Dockerfile
  restapi/api.ts
  restapi/server.ts
  restapi/tests/api.test.ts
  webapp/Dockerfile
  webapp/e2e/features/register-form.feature
  webapp/e2e/steps/register-form.steps.ts
Labels: :zap:New, 🔧Implementation, Deployment

#144 Public places management and adding friends
  restapi/package-lock.json
  restapi/src/business/place/PlaceService.ts
  restapi/src/business/place/PlaceServiceImpl.ts
  restapi/src/business/repositories/PlaceRepository.ts
  restapi/src/business/repositories/UserRepository.ts
  restapi/src/business/user/UserService.ts
  restapi/src/business/user/UserServiceImpl.ts
  restapi/src/controllers/places.ts
  restapi/src/controllers/users.ts
  restapi/src/repositories/PlaceRepositoryImpl.ts
  restapi/src/repositories/UserRepositoryImpl.ts
  restapi/src/repositories/pods/PodDataManager.ts
  restapi/src/repositories/pods/PodSessionManager.ts
  restapi/src/repositories/pods/RDFCreator.ts
  webapp/Dockerfile
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/mainPage/LoginForm.tsx
  webapp/src/components/mainPage/NavBar.tsx
  webapp/src/components/mainPage/Profile.test.tsx
  webapp/src/components/mainPage/Profile.tsx
  webapp/src/components/map/CommentForm.tsx
  webapp/src/components/map/CommentList.tsx
  webapp/src/components/map/CreatePlaceWindow.tsx
  webapp/src/components/map/InfoWindow.tsx
  webapp/src/components/map/MapView.tsx
  webapp/src/components/map/SideBar.tsx
  webapp/src/components/ol/map.tsx
  webapp/src/components/ol/ol-types.ts
  webapp/src/components/ol/vector.tsx
  webapp/src/domain/Category.ts
  webapp/src/domain/Place.ts
  webapp/src/index.css
  webapp/src/index.tsx
  webapp/src/setupTests.ts
  webapp/src/test/App.test.tsx
  webapp/src/test/mainPage/Profile.test.tsx
  webapp/src/test/map/CommentForm.test.tsx
  webapp/src/test/map/CommentList.test.tsx
  webapp/src/test/map/CreatePlaceWindow.test.tsx
  webapp/src/test/map/InfoWindow.test.tsx
  webapp/src/test/map/SideBar.test.tsx
Labels: :zap:New, 🔧Implementation

#145 Fully public sites implemented and added categories to places
  restapi/src/controllers/places.ts
  restapi/src/controllers/users.ts
  webapp/public/index.html
  webapp/public/logo.png
  webapp/public/manifest.json
  webapp/src/App.css
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/LoadingSpinner.tsx
  webapp/src/components/mainPage/Home.tsx
  webapp/src/components/mainPage/LoginForm.tsx
  webapp/src/components/mainPage/NavBar.tsx
  webapp/src/components/mainPage/SlideShow.tsx
  webapp/src/components/map/CommentForm.tsx
  webapp/src/components/map/CommentList.tsx
  webapp/src/components/map/CreatePlaceWindow.tsx
  webapp/src/components/map/FilterCategory.tsx
  webapp/src/components/map/FriendPanel.tsx
  webapp/src/components/map/InfoWindow.tsx
  webapp/src/components/map/MapView.tsx
  webapp/src/components/map/PictureSelector.tsx
  webapp/src/components/map/SideBar.tsx
  webapp/src/components/ol/vector.tsx
  webapp/src/domain/Category.ts
  webapp/src/images-places/Londres.jpg
  webapp/src/images-places/Madrid.jpg
  webapp/src/images-places/eii.jpg
  webapp/src/images-places/nueva-york.jpg
  webapp/src/images-places/paris.jpg
  webapp/src/index.css
  webapp/src/test/map/CommentForm.test.tsx
  webapp/src/test/map/CreatePlaceWindow.test.tsx
  webapp/src/test/map/InfoWindow.test.tsx
  webapp/src/test/map/SideBar.test.tsx
Labels: :arrow_double_up:Improvement, :zap:New
